
version: '3.7'

services:

  bg:
    build:
      context: app
      args: [ COMMIT_SHA, BG_PORT ]
    image: ${BG_IMAGE}
    init: true
    container_name: bg-container
    ports: [ "${BG_PORT}:${BG_PORT}" ]
    user: nobody
    read_only: true
    volumes:
      - ./app/scores:/bg-scores:rw
    restart: "no"
    tmpfs: [ "/tmp:exec,mode=1777" ]
